name: build 10.0

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  DLL_ID: ${{secrets.DLL_ID_10}} # NET버전
  UPLOAD_MODURE: "Y"
  PUSH_NUGET: "Y"
  PASSWORD: ${{secrets.PASSWORD}}

jobs:
  build10:
    runs-on: ubuntu-latest
    env:
      DLL_PATH: "${{vars.NAMESPACE}}(net10.0)/bin/Release/net10.0/${{vars.NAMESPACE}}.dll" # NET버전
      PROJECT_PATH: "${{vars.NAMESPACE}}(net10.0)" # NET버전
      METAFRM_UPLOADMODULE_URL: "https://download.metafrm.net/github/MetaFrameworkManagementSystemUploadModule10.0.zip" # NET버전
      METAFRM_UPLOADMODULE_ZIP: "temp/MetaFrameworkManagementSystemUploadModule10.0.zip" # NET버전
      METAFRM_UPLOADMODULE_FILE: "temp/MetaFrameworkManagementSystemUploadModule.dll"

    steps:
    - uses: actions/checkout@v6
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x # NET버전

    - name: Setup NuGet
      if: runner.os != 'Windows'
      uses: NuGet/setup-nuget@v2
      with:
        nuget-version: latest
        
    - name: Install MAUI Workload (Windows)
      if: runner.os == 'Windows'
      run: dotnet workload install maui --ignore-failed-sources
      
    - name: mkdir temp (Windows)
      run: mkdir -p temp


    - name: Download Upload Module
      if: runner.os != 'Windows'
      run: wget -q "${{ env.METAFRM_UPLOADMODULE_URL }}" -O "${{ env.METAFRM_UPLOADMODULE_ZIP }}"

    - name: Download Upload Module (Windows)
      if: runner.os == 'Windows'
      run: powershell -Command "Invoke-WebRequest -Uri '${{ env.METAFRM_UPLOADMODULE_URL }}' -OutFile '${{ env.METAFRM_UPLOADMODULE_ZIP }}'"

    - name: Unzip
      if: runner.os != 'Windows'
      run: unzip -q "${{ env.METAFRM_UPLOADMODULE_ZIP }}" -d temp
      
    - name: Unzip (Windows)
      if: runner.os == 'Windows'
      run: powershell -Command "Expand-Archive -Path '${{ env.METAFRM_UPLOADMODULE_ZIP }}' -DestinationPath 'temp' -Force"


    - name: Restore dependencies
      id: ST1
      run: dotnet restore "${{env.PROJECT_PATH}}"
    - name: if failure
      if: ${{ failure()}}
      run: dotnet "${{env.METAFRM_UPLOADMODULE_FILE}}" "${{secrets.METAFRM_UPLOADMODULE_ACCESSKEY}}" "${{github.event.pusher.email}}^${{env.PASSWORD}}" "notification" "Restore dependencies Fail !!" "${{env.DLL_PATH}}" "${{vars.NAMESPACE}}"


    - name: Build Debug
      id: ST2
      working-directory: ${{ env.PROJECT_PATH }}
      run: dotnet build -c Debug --no-restore -v minimal
    - name: if failure
      if: ${{ failure() && steps.ST1.outcome != 'failure' }}
      run: dotnet "${{env.METAFRM_UPLOADMODULE_FILE}}" "${{secrets.METAFRM_UPLOADMODULE_ACCESSKEY}}" "${{github.event.pusher.email}}^${{env.PASSWORD}}" "notification" "Build Debug Fail !!" "${{env.DLL_PATH}}" "${{vars.NAMESPACE}}"

    - name: Test Debug
      id: ST3
      working-directory: ${{ env.PROJECT_PATH }}
      run: dotnet test -c Debug --no-build --verbosity normal
    - name: if failure
      if: ${{ failure() && steps.ST1.outcome != 'failure' && steps.ST2.outcome != 'failure' }}
      run: dotnet "${{env.METAFRM_UPLOADMODULE_FILE}}" "${{secrets.METAFRM_UPLOADMODULE_ACCESSKEY}}" "${{github.event.pusher.email}}^${{env.PASSWORD}}" "notification" "Test Debug Fail !!" "${{env.DLL_PATH}}" "${{vars.NAMESPACE}}"

    - name: Build Release
      id: ST4
      working-directory: ${{ env.PROJECT_PATH }}
      run: dotnet build -c Release --no-restore -v minimal
    - name: if failure
      if: ${{ failure() && steps.ST1.outcome != 'failure' && steps.ST2.outcome != 'failure' && steps.ST3.outcome != 'failure' }}
      run: dotnet "${{env.METAFRM_UPLOADMODULE_FILE}}" "${{secrets.METAFRM_UPLOADMODULE_ACCESSKEY}}" "${{github.event.pusher.email}}^${{env.PASSWORD}}" "notification" "Build Release Fail !!" "${{env.DLL_PATH}}" "${{vars.NAMESPACE}}"
      
    - name: Test Release
      id: ST5
      working-directory: ${{ env.PROJECT_PATH }}
      run: dotnet test -c Release --no-build --verbosity normal
    - name: if failure
      if: ${{ failure() && steps.ST1.outcome != 'failure' && steps.ST2.outcome != 'failure' && steps.ST3.outcome != 'failure' && steps.ST4.outcome != 'failure' }}
      run: dotnet "${{env.METAFRM_UPLOADMODULE_FILE}}" "${{secrets.METAFRM_UPLOADMODULE_ACCESSKEY}}" "${{github.event.pusher.email}}^${{env.PASSWORD}}" "notification" "Test Release Fail !!" "${{env.DLL_PATH}}" "${{vars.NAMESPACE}}"
      

    - name: Upload Module
      id: ST6
      if: env.UPLOAD_MODURE == 'Y'
      run: dotnet "${{env.METAFRM_UPLOADMODULE_FILE}}" "${{secrets.METAFRM_UPLOADMODULE_ACCESSKEY}}" "${{github.event.pusher.email}}^${{env.PASSWORD}}" "upload" ${{env.DLL_ID}} "${{env.DLL_PATH}}" "${{vars.NAMESPACE}}"
    - name: if failure
      if: ${{ failure() && steps.ST1.outcome != 'failure' && steps.ST2.outcome != 'failure' && steps.ST3.outcome != 'failure' && steps.ST4.outcome != 'failure' && steps.ST5.outcome != 'failure' }}
      run: dotnet "${{env.METAFRM_UPLOADMODULE_FILE}}" "${{secrets.METAFRM_UPLOADMODULE_ACCESSKEY}}" "${{github.event.pusher.email}}^${{env.PASSWORD}}" "notification" "Upload Module Fail !!" "${{env.DLL_PATH}}" "${{vars.NAMESPACE}}"


    - name: Pack nugets
      id: ST7
      if: env.PUSH_NUGET == 'Y'
      run: dotnet pack "${{env.PROJECT_PATH}}"  -c Release --no-build --output .
    - name: if failure
      if: ${{ failure() && steps.ST1.outcome != 'failure' && steps.ST2.outcome != 'failure' && steps.ST3.outcome != 'failure' && steps.ST4.outcome != 'failure' && steps.ST5.outcome != 'failure' && steps.ST6.outcome != 'failure' }}
      run: dotnet "${{env.METAFRM_UPLOADMODULE_FILE}}" "${{secrets.METAFRM_UPLOADMODULE_ACCESSKEY}}" "${{github.event.pusher.email}}^${{env.PASSWORD}}" "notification" "Pack nugets Fail !!" "${{env.DLL_PATH}}" "${{vars.NAMESPACE}}"
      
    - name: Push to NuGet
      id: ST8
      if: env.PUSH_NUGET == 'Y'
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_AUTH_TOKEN}} --source https://api.nuget.org/v3/index.json
    - name: if failure
      if: ${{ failure() && steps.ST1.outcome != 'failure' && steps.ST2.outcome != 'failure' && steps.ST3.outcome != 'failure' && steps.ST4.outcome != 'failure' && steps.ST5.outcome != 'failure' && steps.ST6.outcome != 'failure' && steps.ST7.outcome != 'failure' }}
      run: dotnet "${{env.METAFRM_UPLOADMODULE_FILE}}" "${{secrets.METAFRM_UPLOADMODULE_ACCESSKEY}}" "${{github.event.pusher.email}}^${{env.PASSWORD}}" "notification" "Push to NuGet Fail !!" "${{env.DLL_PATH}}" "${{vars.NAMESPACE}}"
      

    - name: Completed
      run: dotnet "${{env.METAFRM_UPLOADMODULE_FILE}}" "${{secrets.METAFRM_UPLOADMODULE_ACCESSKEY}}" "${{github.event.pusher.email}}^${{env.PASSWORD}}" "notification" "CI/CD Completed !!" "${{env.DLL_PATH}}" "${{vars.NAMESPACE}}"